site_name: Introduction to Programming
site_url: https://3dcdsc.github.io/
docs_dir: docs/

repo_name: 'Introduction_to_Programming'
repo_url: 'https://github.com/3DCdsc/Introduction_to_Programming'

# Copyright
copyright: Digital Design and Development Club (3DC) &copy; 2019 - 2021. All rights reserved.

# Theme Configuration
theme:
  name: material
  language: en
  favicon: imgs/code.svg
  icon:
    logo: fontawesome/solid/code
  features:
    # - navigation.tabs
    - navigation.expand
  palette:
    scheme: slate
    primary: teal
    accent: indigo

# Extensions
# https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
markdown_extensions:
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/buttons/#attribute-list
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - pymdownx.caret # handling sub- and superscripts
  - pymdownx.mark # highlighting of text
  - pymdownx.tilde # strikethrough of text
  - pymdownx.keys # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys
  - pymdownx.tabbed # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#tabbed
  - pymdownx.details # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#details
  - pymdownx.highlight # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#superfences
  - pymdownx.smartsymbols # supporting special characters like copyright symbol (c)
  - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/mathjax/#arithmatex
      generic: true
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/#tasklist
      custom_checkbox: true
      clickable_checkbox: true
  - toc: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
      permalink: true

# Extra Style
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/3DCdsc
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/3dcdsc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCF56lQD1HWv-0uOQSXrTmLw
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sutd3dc/
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/C_Nni1C77ZlOVTdjU4yf4Q

# Navigation Menu
nav:
  - Overview: "index.md"
  - Demo: "demo.md"
  - Workshop Materials:
    - Day 1: "Day_1/day_1.md"
    - Day 2: "Day_2/day_2.md"

